package sudojo.client.model.net;

public enum Comando {
	LOG,
	GET_ALLIEVI,
	ALL_PAGAMENTI,
	PAGAMENTI_BY_ISCRITTO,
	GET_EVENTI,
	CREA_EVENTO,
	MODIFICA_EVENTO,
	CANCELLA_EVENTO,
	CREA_AVVISO,
	GET_DOC,
	CREA_AFFILIATO,
	MODIFICA_AFFILIATO,
	RIGENERA_PSWD,
	GET_ISCRITTI,
	CREA_SCHEDA,
	GET_AVVISI,
	CREA_DOC,
	GET_BUDO,
	PRESENZE,
	AGGIORNA_BUDOPASS_SEMINARIO,
	AGGIORNA_BUDOPASS_COMPETIZIONE,
	AGGIORNA_BUDOPASS_GRADO,
	CREA_RICEVUTE
}
